### ISSUE TITLE
Setup.py "Open3d is not defined"

### ISSUE THREAD

**Issue by carboncode67** [porteratzo/TreeTool#5]
Hello, 
Forgive my ignorance if this is a simple issue, I am relatively new to python and have previously only installed packages with pip. I was able to follow your instructions in setting up the environment but when I tried to use setuptools and setup.py I get errors that state either "no such file or directory" or "open3 is not defined" which I believe is referring to the first "install_requires" package in the setup.py script. Do you have any instructions on installing the code itself?

**Comment by porteratzo** [comment]
Hi, actually the setup.py is not actually ready yet, it's something I was working on but didn't conclude. Sorry for the confusion.

**Comment by carboncode67** [comment]
Thanks for your fast response! is there any way to get the code running as is?

**Comment by porteratzo** [comment]
Hi, sorry for the late reply. The best way to run the code is to install as mentioned in the README and then start a session of jupyter notebook. You can then open the QuickDemo notebook and load your point cloud and follow the steps along with visualizations of what the software is doing.

________________________________

**Comment by carboncode67** [comment]
I may be missing something but I do not see any instructions in the Readme that describe how to install treetool other than the required packages which I installed.

**Comment by porteratzo** [comment]
Oh okay, currently we have no script to install TreeTool , if you want to use it outside the TreeTool directory you would need to add it to your path. You can use something like
import sys
sys.path.append('/*path to treetool dir*/TreeTool')
you should then be able to import TreeTool funtions like below.
import TreeTool.seg_tree as seg_tree
import TreeTool.utils as utils

________________________________
